//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dharvik.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DharvikEntities1 : DbContext
    {
        public DharvikEntities1()
            : base("name=DharvikEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill1> Bill1 { get; set; }
        public virtual DbSet<Item1> Item1 { get; set; }
        public virtual DbSet<MyOrder> MyOrders { get; set; }
        public virtual DbSet<OBill> OBills { get; set; }
        public virtual DbSet<QBill> QBills { get; set; }
        public virtual DbSet<RecipesDet> RecipesDets { get; set; }
        public virtual DbSet<RecipesDet1> RecipesDet1 { get; set; }
        public virtual DbSet<syNavigationNode> syNavigationNodes { get; set; }
        public virtual DbSet<syResource> syResources { get; set; }
        public virtual DbSet<syResourceType> syResourceTypes { get; set; }
        public virtual DbSet<syRoleResource> syRoleResources { get; set; }
        public virtual DbSet<syRole> syRoles { get; set; }
        public virtual DbSet<syRolesResourcesLevel> syRolesResourcesLevels { get; set; }
        public virtual DbSet<syUsersRole> syUsersRoles { get; set; }
        public virtual DbSet<tbl_BankMaster> tbl_BankMaster { get; set; }
        public virtual DbSet<tbl_Bill> tbl_Bill { get; set; }
        public virtual DbSet<tbl_CallHistory> tbl_CallHistory { get; set; }
        public virtual DbSet<tbl_Chattter> tbl_Chattter { get; set; }
        public virtual DbSet<tbl_ChatViewedBy> tbl_ChatViewedBy { get; set; }
        public virtual DbSet<tbl_Client> tbl_Client { get; set; }
        public virtual DbSet<tbl_CustAccount> tbl_CustAccount { get; set; }
        public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
        public virtual DbSet<tbl_EMails> tbl_EMails { get; set; }
        public virtual DbSet<tbl_EmailTemplates> tbl_EmailTemplates { get; set; }
        public virtual DbSet<tbl_EmpAccount> tbl_EmpAccount { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_Expenses> tbl_Expenses { get; set; }
        public virtual DbSet<tbl_FromAddress> tbl_FromAddress { get; set; }
        public virtual DbSet<tbl_Invoice> tbl_Invoice { get; set; }
        public virtual DbSet<tbl_Item> tbl_Item { get; set; }
        public virtual DbSet<tbl_Notes> tbl_Notes { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_Quotation> tbl_Quotation { get; set; }
        public virtual DbSet<tbl_Supplier> tbl_Supplier { get; set; }
        public virtual DbSet<tbl_Transaction> tbl_Transaction { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblLoginHistory> tblLoginHistories { get; set; }
        public virtual DbSet<tblMessage> tblMessages { get; set; }
        public virtual DbSet<tblPagesLoginHistory> tblPagesLoginHistories { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<Invoice1> Invoice1 { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Recipes1> Recipes1 { get; set; }
        public virtual DbSet<tbl_SuppAccount> tbl_SuppAccount { get; set; }
        public virtual DbSet<tbl_Category> tbl_Category { get; set; }
        public virtual DbSet<tbl_Purchase> tbl_Purchase { get; set; }
    }
}
