//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dharvik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class QBill
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public string ItemId { get; set; }
        public decimal ItemQty { get; set; }
        public decimal ItemSaleAmt { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public decimal Rate { get; set; }
        public Nullable<decimal> Discount { get; set; }
    }
}
