//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dharvik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class syNavigationNode
    {
        public int NodeID { get; set; }
        public int DisplayIndex { get; set; }
        public int ResourceId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> IsPopupWindow { get; set; }
    }
}
